'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Clientes
    
    '''<summary>
    '''scrmngClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrmngClientes As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating
    
    '''<summary>
    '''updpnlClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlClientes As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''TabPanelCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelCadastro As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAtualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAtualizar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExcluir As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConsultar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkRelatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRelatorio As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExcel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkDuplicar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDuplicar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkFichaCadastral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFichaCadastral As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHelp As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUsuario As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUsuarios As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEmpresas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpresas As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtReduzido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReduzido As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCpfCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCpfCnpj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodigoEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoEndereco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnConsultaCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultaCadastro As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgFicha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFicha As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ddlSituacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSituacao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgBloqueio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBloqueio As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNomeFantasia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeFantasia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''radMasculino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMasculino As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''radFeminino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radFeminino As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespondencia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCorrespondencia As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgLimparEndCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLimparEndCorrespondencia As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtCep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCep As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgCep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCep As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgConsultaCep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgConsultaCep As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndereco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplemento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBairro As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPais As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCidade As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodMunicipio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtAlteraCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtAlteraCidade As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ddlRegiao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegiao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlMicroRegiao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMicroRegiao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEstadoCivil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoCivil As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtDataNascimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataNascimento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataCliente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlNaturalidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNaturalidade As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCidadeNatural control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCidadeNatural As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodigoInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoInscricao As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInscricao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInscricao As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkIsento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsento As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRG As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOutrosTelefones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOutrosTelefones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHabilitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHabilitacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmailNFE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailNFE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRegistros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegistros As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSite As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUltimaAtualizacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUltimaAtualizacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRNTRCTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRNTRCTransportador As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkApenasAVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApenasAVista As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CkExcell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkExcell As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''HiddenUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenUpload As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''filUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile
    
    '''<summary>
    '''imgFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFoto As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''TabPanelTiposDeClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelTiposDeClientes As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''chkListTipoDeCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListTipoDeCliente As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''TabPanelContatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelContatos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoCONT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoCONT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparCONT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparCONT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaCONT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaCONT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtNomeContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexContato As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtFuncaoContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuncaoContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelefoneContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefoneContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlBancoContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBancoContato As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEmailContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAgenciaContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgenciaContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDGAgContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDGAgContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCtaContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtaContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDGCtaContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDGCtaContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObservacaoContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoContato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridContatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridContatos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelDependentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelDependentes As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtNomeDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexDependente As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtRGDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRGDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPFDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPFDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTipoDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoDependente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNascimentoDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNascimentoDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProfissaoDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProfissaoDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCustoDependente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustoDependente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridDependentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDependentes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelContasBancárias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelContasBancárias As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoCB As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparBC As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaBC As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''HgridRowIndexContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexContaBancaria As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddlBancoContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBancoContaBancaria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAgenciaContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgenciaContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDGAgContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDGAgContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCtaContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCtaContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDGCtaContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDGCtaContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlEstadoContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoContaBancaria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTipoConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoConta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAtivo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtCidadeContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCidadeContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPracaContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPracaContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObservacaoContaBancaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoContaBancaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridContasBancarias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridContasBancarias As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelCultura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelCultura As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoCULT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoCULT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparCULT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparCULT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaCULT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaCULT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''HgridRowIndexCultura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexCultura As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddlSafra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSafra As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCultura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCultura As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProdutividade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdutividade As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtConsumoProprio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumoProprio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtComprometido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComprometido As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEstimativaDeEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstimativaDeEntrega As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObservacaoSafra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoSafra As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridCultura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCultura As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelVeículos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelVeículos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoV As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparV As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaV As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtPlacaVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacaVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexVeiculo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddlTipoVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoVeiculo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAnoVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnoVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFabricanteVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFabricanteVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtModeloVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModeloVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataAvaliacaoVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAvaliacaoVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrOficialVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrOficialVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrMoedaVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrMoedaVeiculo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkVeiculoOnerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVeiculoOnerado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''gridVeiculos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridVeiculos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelEquipamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelEquipamentos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButton7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton7 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtRegistroEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegistroEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexEquipamento As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddlTipoEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoEquipamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAnoEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnoEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFabricanteEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFabricanteEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMarcaEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarcaEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtModeloEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModeloEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataAvaliacaoEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAvaliacaoEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrOficialEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrOficialEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrMoedaEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrMoedaEquipamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkEquipamentoOnerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEquipamentoOnerado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''gridEquipamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridEquipamentos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelImóveis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelImóveis As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoI As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparI As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaI As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtCodigoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexImovel As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtDescricaoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkOneradoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOneradoImovel As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlEstadoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoImovel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCidadeImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCidadeImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAreaTotalImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaTotalImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAreaConstruidaImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaConstruidaImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlUnidadeImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidadeImovel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtRegistroImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegistroImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCartorioImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCartorioImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataAvaliacaoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAvaliacaoImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrOficialImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrOficialImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrMoedaImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrMoedaImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObservacaoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoImovel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridImoveis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridImoveis As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelArrendantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelArrendantes As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButton8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton8 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gridArrendantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridArrendantes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelRepresentantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelRepresentantes As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoR As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparR As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaR As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepresentante As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodigoRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoRepresentante As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HgridRowIndexRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexRepresentante As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRepresentante As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkPrincipalRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrincipalRepresentante As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''gridRepresentantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridRepresentantes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelSócios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelSócios As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtSocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSocio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodigoSocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoSocio As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HgridRowIndexSocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexSocio As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSocio As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtParticipacaoSocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParticipacaoSocio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridSocios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridSocios As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelMatrículas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelMatrículas As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoM As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparM As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaM As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtNumeroMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridRowIndexMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexMatricula As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtDataAvaliacaoMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAvaliacaoMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAreaMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVlrOficialMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVlrOficialMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRegistroMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegistroMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLivroMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLivroMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFolhaMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFolhaMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlEstadoMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoMatricula As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtMunicipioMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipioMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridMatriculas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMatriculas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelFinanciamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelFinanciamentos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoF As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparF As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaF As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtFinanciador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinanciador As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodigoFinanciador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoFinanciador As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HgridRowIndexFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridRowIndexFinanciamento As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnFinanciador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinanciador As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtCodigoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTipoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSafraFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSafraFinanciamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlGrupoProdutoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGrupoProdutoFinanciamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlProdutoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProdutoFinanciamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtParcelaFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParcelaFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVencimentoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVencimentoFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlMoedaFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoedaFinanciamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtQuantidadeFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantidadeFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOficialFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOficialFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMoedaFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoedaFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObservacaoFinanciamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoFinanciamento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridFinanciamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridFinanciamentos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelReceitasDespesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelReceitasDespesas As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoRD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparRD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaRD As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAno As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReceitaDespesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReceitaDespesa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTipoReceitaDespesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoReceitaDespesa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtValorAnoRecDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorAnoRecDes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescricaoRecDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoRecDes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HgridIndexRecDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HgridIndexRecDes As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''gridReceitasDespesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridReceitasDespesas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelCentrosDeCustos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelCentrosDeCustos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoCC As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparCC As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjuda As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlCentroDeCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCentroDeCusto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtPercResponsavelCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercResponsavelCC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabSubstitutoTributario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabSubstitutoTributario As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoST As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparST As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaST As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtSubTributario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubTributario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlEstadoST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoST As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gridST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridST As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabDocumentos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''txtDescricaoDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoDocumento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNomeDoArquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDoArquivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fupArquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fupArquivo As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''gridDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDocumentos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''updpnlAdicionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlAdicionar As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnAdicionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdicionar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TabTabelaPrecos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabTabelaPrecos As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lnkNovoTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovoTP As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimparTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimparTP As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjudaTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjudaTP As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtRepresentanteTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepresentanteTP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTabelasDePrecos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTabelasDePrecos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gridTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTP As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelConsulta As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''gridConsultaCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridConsultaCliente As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnImpressaoClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImpressaoClientes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ucArrendante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucArrendante As Global.NGS.Web.UI.ucArrendante
    
    '''<summary>
    '''ucConsultaCep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaCep As Global.NGS.Web.UI.ucConsultaCep
    
    '''<summary>
    '''ucConsultaClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaClientes As Global.NGS.Web.UI.ucConsultaClientes
    
    '''<summary>
    '''ucConsultaCodMunicipios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaCodMunicipios As Global.NGS.Web.UI.ucConsultaCodMunicipios
    
    '''<summary>
    '''ucConsultaEstados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaEstados As Global.NGS.Web.UI.ucConsultaEstados
    
    '''<summary>
    '''ucConsultaCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaCadastro As Global.NGS.Web.UI.ucConsultaCadastro
End Class
