'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Laudo

    '''<summary>
    '''scrmngsLaudoDePesagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrmngsLaudoDePesagem As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating

    '''<summary>
    '''updpnlLaudoDePesagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlLaudoDePesagem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''TabPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''btnEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmpresa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNomeDaEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDaEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCnpjDaEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCnpjDaEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMunicipioDaEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipioDaEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEstadoDaEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstadoDaEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndEmpresa As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtLaudo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLaudo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEntradaSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntradaSaida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRomaneio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRomaneio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSituacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSituacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkConsolidarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsolidarCliente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNomeDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCnpjDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCnpjDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndCliente As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMunicipioDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipioDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEstadoDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstadoDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnderecoDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnderecoDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComplementoDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplementoDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBairroDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBairroDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCepDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCepDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTelefoneDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefoneDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInscricaoDoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInscricaoDoCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPedido As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPedido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgExtratoPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgExtratoPedido As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hdnSaldoPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSaldoPedido As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAutorizacaoDeRetirada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAutorizacaoDeRetirada As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnRateio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRateio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''imgRateio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRateio As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ddlOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOperacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSubOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubOperacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSafra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSaldoPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaldoPedido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRateio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRateio As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDestinatario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNomeDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCnpjDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCnpjDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnderecoDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnderecoDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComplementoDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplementoDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBairroDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBairroDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMunicipioDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipioDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEstadoDoDestinatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstadoDoDestinatario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuantidadeDestino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantidadeDestino As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgQuantidadeRateio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuantidadeRateio As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlDestinatarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDestinatarios As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridRateio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridRateio As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnDepositante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDepositante As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtDepositante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepositante As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndDepositante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndDepositante As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnDeposito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeposito As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtDeposito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeposito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndDeposito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndDeposito As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransportador As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportador As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndTransportador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnPlaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlaca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtPlaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorista As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCodigoEndMotorista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigoEndMotorista As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnViaDeTransporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnViaDeTransporte As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnPesagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPesagem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEncerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEncerrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncluir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReimprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReimprimir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMovimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMovimento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''radImpressora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radImpressora As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radArquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radArquivo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtNumeroDeCopias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroDeCopias As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAcessoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcessoUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlImpressora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlImpressora As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPorta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPorta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcesso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnTesteBalanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTesteBalanca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnBaudRateBalanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBaudRateBalanca As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDataBits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDataBits As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnParity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnParity As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnStopBits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStopBits As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEletronico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEletronico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlTabelaDeClassificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTabelaDeClassificacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblPesagemMecanica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPesagemMecanica As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkLiberado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLiberado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divAnalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnalise As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridDescontos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDescontos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnCalcular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalcular As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtPrimeiraPesagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimeiraPesagem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSegundaPesagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSegundaPesagem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoBruto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoBruto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDesconto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesconto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLiquido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLiquido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLerPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLerPeso As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAutorizacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutorizacao As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNotaProdutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotaProdutor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSerieNotaProdutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerieNotaProdutor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoNotaProdutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoNotaProdutor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHistorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistorico As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TabPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''gdvLaudo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvLaudo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdnControlePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnControlePopup As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ucConsultaEmpresas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaEmpresas As Global.NGS.Web.UI.ucConsultaEmpresas

    '''<summary>
    '''ucConsultaClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaClientes As Global.NGS.Web.UI.ucConsultaClientes

    '''<summary>
    '''ucConsultaClientesDireto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaClientesDireto As Global.NGS.Web.UI.ucConsultaClientesDireto

    '''<summary>
    '''ucConsultaPedidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaPedidos As Global.NGS.Web.UI.ucConsultaPedidos

    '''<summary>
    '''ucConsultaAutorizacaoDeRetirada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaAutorizacaoDeRetirada As Global.NGS.Web.UI.ucConsultaAutorizacaoDeRetirada

    '''<summary>
    '''ucConsultaPlacas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaPlacas As Global.NGS.Web.UI.ucConsultaPlacas

    '''<summary>
    '''ucConsultaEstados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaEstados As Global.NGS.Web.UI.ucConsultaEstados

    '''<summary>
    '''ucConsultaCodMunicipios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaCodMunicipios As Global.NGS.Web.UI.ucConsultaCodMunicipios
End Class
