'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LiberarPermissoes

    '''<summary>
    '''scrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrm As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating

    '''<summary>
    '''updLiberarPermissoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updLiberarPermissoes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hdfGrupoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGrupoId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfProcessoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfProcessoId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lnkAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjuda As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updpnlDivGrupos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlDivGrupos As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstGrupos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstGrupos As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''updpnlDivProcessos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlDivProcessos As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstProcessos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProcessos As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''updpnlDivPermissoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlDivPermissoes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstPermissoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstPermissoes As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''btnAtualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAtualizar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updpnlDivUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlDivUsuarios As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUsuarios As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''updpnlParticipantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlParticipantes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstParticipantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstParticipantes As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''txtGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrupo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcesso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAjuda As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSair As Global.System.Web.UI.WebControls.Button
End Class
