'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PedidosPendentes

    '''<summary>
    '''scmngPedidosPendentesDeVendas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scmngPedidosPendentesDeVendas As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating

    '''<summary>
    '''updpnlPedidosPendentesDeVendas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlPedidosPendentesDeVendas As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lnkRelatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRelatorio As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimpar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjuda As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkRelAnalitico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRelAnalitico As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRelResumoClienteProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRelResumoClienteProduto As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRelResumoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRelResumoCliente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkConsolidarEmpresasApresentacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsolidarEmpresasApresentacao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkConsolidarClientesApresentacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsolidarClientesApresentacao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlUnidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidade As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkConsolidarEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsolidarEmpresa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DdlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlEmpresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DdlSafra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSafra As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlClasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClasse As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPeriodo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlDataMovimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataMovimento As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDataInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataInicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkConsolidarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsolidarCliente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCodigoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoCliente As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucSelecaoProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucSelecaoProduto As Global.NGS.Web.UI.ucSelecaoProduto

    '''<summary>
    '''ucConsultaClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsultaClientes As Global.NGS.Web.UI.ucConsultaClientes
End Class
