'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RelatorioDeOrdensDeProducoes
    
    '''<summary>
    '''scrmngOrdemDeProducao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrmngOrdemDeProducao As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating
    
    '''<summary>
    '''updpnlOrdemDeProducao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlOrdemDeProducao As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lnkRelatorioPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRelatorioPDF As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkRelatorioExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRelatorioExcel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjuda As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlUnidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidade As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlEmpresa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtDataInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbDtMov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDtMov As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbDtVen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDtVen As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbOrdem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbOrdem As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbOPrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbOPrd As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbOPrdNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbOPrdNome As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbAberta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAberta As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbEncerrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbEncerrada As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbCancelada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCancelada As Global.System.Web.UI.WebControls.RadioButton
End Class
