'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetoresXCentrosDeCusto

    '''<summary>
    '''scmngSetoresXCentrosDeCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scmngSetoresXCentrosDeCusto As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ajaxUpdating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxUpdating As Global.Orea.WebControls.AjaxUpdating

    '''<summary>
    '''updpnlSetoresXCentrosDeCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlSetoresXCentrosDeCusto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkAtualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAtualizar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkRelatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRelatorio As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkAjuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAjuda As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GridSetores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridSetores As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridCentrosDeCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridCentrosDeCusto As Global.System.Web.UI.WebControls.GridView
End Class
