INSERT INTO TiposCampo VALUES ('CalendarBox', 0, 0, 0)
INSERT INTO TiposCampo VALUES ('CheckBox', 0, 0, 0)
INSERT INTO TiposCampo VALUES ('DescriptionSearch', 0, 1, 1)
INSERT INTO TiposCampo VALUES ('DropDownList', 1, 0, 0)
INSERT INTO TiposCampo VALUES ('NumberBox', 0, 0, 0)
INSERT INTO TiposCampo VALUES ('OptionList', 1, 0, 0)
INSERT INTO TiposCampo VALUES ('TextBox', 0, 0, 0)
INSERT INTO Telas VALUES ('Estados', 'Estados', 0, 1, 1)
INSERT INTO TelaCampos VALUES ('Estados_txtEstadoId', 'Estados', 'Sigla', 'Estado_Id', 2, 1, 'TextBox', 1, 1, 'String')
INSERT INTO TelaCampos VALUES ('Estados_txtEstadoNome', 'Estados', 'Nome', 'Descricao', 50, 1, 'TextBox', 2, 0, 'String')
INSERT INTO ListaSelecao VALUES ('Estados', 'SELECT	Estados.Estado_Id, Estados.Descricao FROM Estados')
