'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucEmitirCTe

    '''<summary>
    '''updpnlEmitirCTe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlEmitirCTe As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tabDados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDados As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tabEmbarque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabEmbarque As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lnkConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConfirmar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLimpar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkFechar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFechar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtRemetenteNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteComplemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteBairro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemetenteInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemetenteInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioComplemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioBairro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDestinatarioInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinatarioInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnTomador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTomador As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTomadorEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorComplemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorBairro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTomadorInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTomadorInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridNFe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridNFe As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtEmbarqueNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEmbarque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmbarque As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtEmbarqueEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmbarqueComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueComplemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmbarqueBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueBairro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmbarqueCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmbarqueCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmbarqueInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbarqueInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEntrega As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtEntregaEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaComplemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaBairro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntregaInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntregaInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNFe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNFe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnConsultarNFe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultarNFe As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtQuantidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantidade As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnitario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOperacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEntSai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntSai As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCfop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCfop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rdContratoSim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdContratoSim As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdoContratoNao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoContratoNao As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdPedagioSim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPedagioSim As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdPedagioNao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPedagioNao As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlTipoCTe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoCTe As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEncargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEncargos As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridEncargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridEncargos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabTransporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabTransporte As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''btnTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransportador As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTransportadorNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransportadorRNTRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorRNTRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransportadorEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransportadorCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransportadorCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransportadorInscricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransportadorInscricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPlacaTrator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlacaTrator As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCPlaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPlaca As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlacaCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacaCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlacaEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacaEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlacaRNTRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacaRNTRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlacaProprietario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlacaProprietario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCPlaca02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPlaca02 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca2Cidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca2Cidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca2Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca2Estado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca2RNTRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca2RNTRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca2Proprietario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca2Proprietario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCPlaca03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPlaca03 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca3Cidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca3Cidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca3Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca3Estado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca3RNTRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca3RNTRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca3Proprietario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca3Proprietario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCPlaca04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPlaca04 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca4Cidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca4Cidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca4Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca4Estado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca4RNTRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca4RNTRC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlaca4Proprietario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca4Proprietario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaEndereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaEndereco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaCidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaCPF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotoristaHabilitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotoristaHabilitacao As Global.System.Web.UI.WebControls.Label
End Class
