'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucNFReferencialSaida

    '''<summary>
    '''updpnlConsultaNFReferencialSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlConsultaNFReferencialSaida As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''liNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liNovo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkFechar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFechar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gridConsultaNFReferencialSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridConsultaNFReferencialSaida As Global.System.Web.UI.WebControls.GridView
End Class
