'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace cheque
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ImpressaoChequesSoap", [Namespace]:="http://www.ngs.com.br/")>  _
    Partial Public Class ImpressaoCheques
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ImprimirChequesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ImprimirChequeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.NGS.Web.UI.My.MySettings.Default.NGS_Web_UI_cheque_ImpressaoCheques
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ImprimirChequesCompleted As ImprimirChequesCompletedEventHandler
        
        '''<remarks/>
        Public Event ImprimirChequeCompleted As ImprimirChequeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ngs.com.br/ImprimirCheques", RequestNamespace:="http://www.ngs.com.br/", ResponseNamespace:="http://www.ngs.com.br/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ImprimirCheques(ByVal Valor() As Double, ByVal ValorExtenso() As String, ByVal Nome() As String, ByVal Cidade() As String, ByVal Data() As Date, ByVal NumeroCheque() As Integer, ByVal CodigoBanco As Integer) As String
            Dim results() As Object = Me.Invoke("ImprimirCheques", New Object() {Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ImprimirChequesAsync(ByVal Valor() As Double, ByVal ValorExtenso() As String, ByVal Nome() As String, ByVal Cidade() As String, ByVal Data() As Date, ByVal NumeroCheque() As Integer, ByVal CodigoBanco As Integer)
            Me.ImprimirChequesAsync(Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ImprimirChequesAsync(ByVal Valor() As Double, ByVal ValorExtenso() As String, ByVal Nome() As String, ByVal Cidade() As String, ByVal Data() As Date, ByVal NumeroCheque() As Integer, ByVal CodigoBanco As Integer, ByVal userState As Object)
            If (Me.ImprimirChequesOperationCompleted Is Nothing) Then
                Me.ImprimirChequesOperationCompleted = AddressOf Me.OnImprimirChequesOperationCompleted
            End If
            Me.InvokeAsync("ImprimirCheques", New Object() {Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco}, Me.ImprimirChequesOperationCompleted, userState)
        End Sub
        
        Private Sub OnImprimirChequesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ImprimirChequesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ImprimirChequesCompleted(Me, New ImprimirChequesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ngs.com.br/ImprimirCheque", RequestNamespace:="http://www.ngs.com.br/", ResponseNamespace:="http://www.ngs.com.br/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ImprimirCheque(ByVal Valor As Double, ByVal ValorExtenso As String, ByVal Nome As String, ByVal Cidade As String, ByVal Data As Date, ByVal NumeroCheque As Integer, ByVal CodigoBanco As Integer) As String
            Dim results() As Object = Me.Invoke("ImprimirCheque", New Object() {Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ImprimirChequeAsync(ByVal Valor As Double, ByVal ValorExtenso As String, ByVal Nome As String, ByVal Cidade As String, ByVal Data As Date, ByVal NumeroCheque As Integer, ByVal CodigoBanco As Integer)
            Me.ImprimirChequeAsync(Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ImprimirChequeAsync(ByVal Valor As Double, ByVal ValorExtenso As String, ByVal Nome As String, ByVal Cidade As String, ByVal Data As Date, ByVal NumeroCheque As Integer, ByVal CodigoBanco As Integer, ByVal userState As Object)
            If (Me.ImprimirChequeOperationCompleted Is Nothing) Then
                Me.ImprimirChequeOperationCompleted = AddressOf Me.OnImprimirChequeOperationCompleted
            End If
            Me.InvokeAsync("ImprimirCheque", New Object() {Valor, ValorExtenso, Nome, Cidade, Data, NumeroCheque, CodigoBanco}, Me.ImprimirChequeOperationCompleted, userState)
        End Sub
        
        Private Sub OnImprimirChequeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ImprimirChequeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ImprimirChequeCompleted(Me, New ImprimirChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ImprimirChequesCompletedEventHandler(ByVal sender As Object, ByVal e As ImprimirChequesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImprimirChequesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ImprimirChequeCompletedEventHandler(ByVal sender As Object, ByVal e As ImprimirChequeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImprimirChequeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
