'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace LerPeso
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LerPeso.IService")>  _
    Public Interface IService
        
        'CODEGEN: Generating message contract since element name TipoDaBalanca from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService/CapturarPeso", ReplyAction:="http://tempuri.org/IService/CapturarPesoResponse")>  _
        Function CapturarPeso(ByVal request As LerPeso.CapturarPesoRequest) As LerPeso.CapturarPesoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CapturarPesoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CapturarPeso", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As LerPeso.CapturarPesoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LerPeso.CapturarPesoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CapturarPesoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TipoDaBalanca As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public DTR As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public RTS As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public ReadBuffer As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public ReceivedBytes As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Porta As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public BaudRate As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public DataBits As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public pParity As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public pStopBits As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TipoDaBalanca As String, ByVal DTR As Boolean, ByVal RTS As Boolean, ByVal ReadBuffer As Integer, ByVal ReceivedBytes As Integer, ByVal Porta As String, ByVal BaudRate As Integer, ByVal DataBits As String, ByVal pParity As Integer, ByVal pStopBits As Integer)
            MyBase.New
            Me.TipoDaBalanca = TipoDaBalanca
            Me.DTR = DTR
            Me.RTS = RTS
            Me.ReadBuffer = ReadBuffer
            Me.ReceivedBytes = ReceivedBytes
            Me.Porta = Porta
            Me.BaudRate = BaudRate
            Me.DataBits = DataBits
            Me.pParity = pParity
            Me.pStopBits = pStopBits
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CapturarPesoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CapturarPesoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As LerPeso.CapturarPesoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LerPeso.CapturarPesoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CapturarPesoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CapturarPesoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CapturarPesoResult As String)
            MyBase.New
            Me.CapturarPesoResult = CapturarPesoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceChannel
        Inherits LerPeso.IService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceClient
        Inherits System.ServiceModel.ClientBase(Of LerPeso.IService)
        Implements LerPeso.IService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LerPeso_IService_CapturarPeso(ByVal request As LerPeso.CapturarPesoRequest) As LerPeso.CapturarPesoResponse Implements LerPeso.IService.CapturarPeso
            Return MyBase.Channel.CapturarPeso(request)
        End Function
        
        Public Function CapturarPeso(ByVal TipoDaBalanca As String, ByVal DTR As Boolean, ByVal RTS As Boolean, ByVal ReadBuffer As Integer, ByVal ReceivedBytes As Integer, ByVal Porta As String, ByVal BaudRate As Integer, ByVal DataBits As String, ByVal pParity As Integer, ByVal pStopBits As Integer) As String
            Dim inValue As LerPeso.CapturarPesoRequest = New LerPeso.CapturarPesoRequest()
            inValue.Body = New LerPeso.CapturarPesoRequestBody()
            inValue.Body.TipoDaBalanca = TipoDaBalanca
            inValue.Body.DTR = DTR
            inValue.Body.RTS = RTS
            inValue.Body.ReadBuffer = ReadBuffer
            inValue.Body.ReceivedBytes = ReceivedBytes
            inValue.Body.Porta = Porta
            inValue.Body.BaudRate = BaudRate
            inValue.Body.DataBits = DataBits
            inValue.Body.pParity = pParity
            inValue.Body.pStopBits = pStopBits
            Dim retVal As LerPeso.CapturarPesoResponse = CType(Me,LerPeso.IService).CapturarPeso(inValue)
            Return retVal.Body.CapturarPesoResult
        End Function
    End Class
End Namespace
